spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  config-location: classpath:mybatis/mybatis.xml
  mapper-locations: classpath:com/cnpc/dao/*.xml
  type-aliases-package: com.cnpc.dao